### ISSUE TITLE
[Bug] Threat match rule fails test

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/detection-rules#1036]
**Describe the bug**
A toml file for the threat match type fails the validation with error:
```
------------------------------------------------------------------------------------ Captured stdout ------------------------------------------------------------------------------------
Loading rules from /rgngit/secops/detections/rules
Loaded 582 rules
Invalid rule file in /rgngit/secops/detections/rules/soc/rgn_ioc_matching_files.toml
Additional properties are not allowed ('threat_query', 'threat_index' were unexpected)
================================================================================ short test summary info ================================================================================
ERROR tests/test_mappings.py - jsonschema.exceptions.ValidationError: Additional properties are not allowed ('threat_query', 'threat_index' were unexpected)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================== 1 error in 7.45s ====================================================================================

```

**To Reproduce**
1. Create a toml file with the following content:
```toml
[metadata]
creation_date = "2021/03/04"
maturity = "production"
updated_date = "2021/03/04"

[rule]
author = ["S.Holzhauer"]
description = '''
A host is communicating with a destination.ip which is known to be malicious and is registered as Indicator Of Compromise.
'''
note = '''
Verify the destination.ip is indeed a malicious ip and try to determine what
on the source is (trying to) communicate with the destination.
source.process for example.


Do not connect to the destination.ip yourself!
'''
index = ["packetbeat-*", "filebeat-*", "heartbeat-*", "apm-*", "logs-*", "metribeat-*", "metrics-*", "winlogbeat-*", "auditbeat-*"]
language = "kuery"
license = "Elastic License"
name = "IOC match on IP address"
risk_score = 100
rule_id = "312971de-17de-405e-8a6a-978d5e9841e2"
severity = "high"
tags = ["ioc", "network"]
type = "threat_match"

query = '''
destination.ip:*
'''

threat_index = ["elastic-tip"]
threat_query = "threat.ip:*"

[[threat_mapping]]
[[threat_mapping.entries]]
field="destination.ip"
type="mapping"
value="threat.ip"

```
2. Run `python -m detection_rules validate-all`
3. Run `python -m detection_rules test`

Both commands will fail with error:
```
------------------------------------------------------------------------------------ Captured stdout ------------------------------------------------------------------------------------
Loading rules from /rgngit/secops/detections/rules
Loaded 582 rules
Invalid rule file in /rgngit/secops/detections/rules/soc/rgn_ioc_matching_files.toml
Additional properties are not allowed ('threat_query', 'threat_index' were unexpected)
================================================================================ short test summary info ================================================================================
ERROR tests/test_mappings.py - jsonschema.exceptions.ValidationError: Additional properties are not allowed ('threat_query', 'threat_index' were unexpected)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================== 1 error in 7.45s ====================================================================================

```

**Expected behavior**
The rule is validated correctly

**Screenshots**
The json result of the TOML:
```json
{
  "threat_mapping": [
    {
      "entries": [
        {
          "field": "destination.ip",
          "type": "mapping",
          "value": "threat.ip"
        }
      ]
    }
  ],
  "metadata": {
    "creation_date": "2021/03/04",
    "maturity": "production",
    "updated_date": "2021/03/04"
  },
  "rule": {
    "author": [
      "S.Holzhauer"
    ],
    "description": "A host is communicating with a destination.ip which is known to be malicious and is registered as Indicator Of Compromise.\n",
    "index": [
      "packetbeat-*",
      "filebeat-*",
      "heartbeat-*",
      "apm-*",
      "logs-*",
      "metribeat-*",
      "metrics-*",
      "winlogbeat-*",
      "auditbeat-*"
    ],
    "language": "kuery",
    "license": "Elastic License",
    "name": "IOC match on IP address",
    "note": "Verify the destination.ip is indeed a malicious ip and try to determine what\non the source is (trying to) communicate with the destination.\nsource.process for example.\n\n\nDo not connect to the destination.ip yourself!\n",
    "query": "destination.ip:*\n",
    "risk_score": 100,
    "rule_id": "312971de-17de-405e-8a6a-978d5e9841e2",
    "severity": "high",
    "tags": [
      "ioc",
      "network"
    ],
    "threat_index": [
      "elastic-tip"
    ],
    "threat_query": "threat.ip:*",
    "type": "threat_match"
  }
}
```
