### ISSUE TITLE
[Bug] Some EQL rules have a `maxspan` longer than the time window

### ISSUE THREAD

**Issue by rw-access** [elastic/detection-rules#1343]
**Describe the bug**
Some EQL rules look like this:
```toml
from = "now-9m"
# ...
query = '''
sequence with maxspan=3h
  [ ... ]
  [ ... ]
'''
```
But the `3h` window is much longer than the actual time range searched (9m). Either the window needs to increase, or `maxspan` should be decreased or removed. In the current state, `maxspan=` has no value.

**Expected behavior**
Unit tests should catch this sort of thing.
