### ISSUE TITLE
[FR] Support Forked Rules

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#1935]
Inspired by https://github.com/elastic/ia-trade-team/issues/24#issuecomment-1079773297

- add a buffer to the lock process to always leave N (~10-100) version spacing
![image](https://user-images.githubusercontent.com/16747370/160256865-0f6adc9c-7dc6-46a8-9369-c50343f6639f.png)

- add an array to the metadata section within the rules to bring awareness to rule devs attention
    - this data resides in the `versions.lock`, but that is buried and easy to overlook
ex:

```toml
[metadata]
other_meta = "values..."
previous_locks = ["7.13", "8.0"]
```
