### ISSUE TITLE
[FR] Adjusted Build-Release Packaging and Manifest to Scope ^7.15 or ^8.0.0

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#1999]
**Is your feature request related to a problem? Please describe.**
This is not a specific problem but more of an enhancement to reduce the duplication of work needed when doing integration artifact releases. Currently our `manifest.yml` files appear as so and thus we need to do one for 7.X series and 8.X series.

```
categories:
  - security
conditions:
  kibana.version: ^8.0.0
description: Prebuilt detection rules for Elastic Security
format_version: 1.0.0
icons:
  - size: 16x16
    src: /img/security-logo-color-64px.svg
    type: image/svg+xml
license: basic
name: security_detection_engine
owner:
  github: elastic/protections
release: ga
title: Prebuilt Security Detection Rules
type: integration
version: 1.0.2
```

As a result we have to do the same process twice for OOB Integrations releases. Below are examples where we do this for 7.x series and 8.x series.

* https://github.com/elastic/ia-trade-team/issues/29 | 7.x Series for 8.2 | [Manifest File from Package](https://github.com/elastic/ia-trade-team/issues/29)
* https://github.com/elastic/ia-trade-team/issues/30 | 8.x Series for 8.2 |[ Manifest File from Package](https://github.com/elastic/package-storage/blob/production/packages/security_detection_engine/1.0.2/manifest.yml)

**Describe the solution you'd like**
Instead, we can adjust this to be like the following, but will need to take into consideration anything else effected that needs adjusted as well for CLI and process related.

```
categories:
  - security
conditions:
  kibana.version: "^7.15.0 || ^8.0.0"
description: Prebuilt detection rules for Elastic Security
format_version: 1.0.0
icons:
  - size: 16x16
    src: /img/security-logo-color-64px.svg
    type: image/svg+xml
license: basic
name: security_detection_engine
owner:
  github: elastic/protections
release: ga
title: Prebuilt Security Detection Rules
type: integration
version: 1.0.3
```

**Describe alternatives you've considered**
No alternatives have been explored at this time.

**Additional context**
Other packages are already using this OR statement to account for both 7.X and 8.X series as linked below to the AWS package.

[AWS Manifest File from Package-Storage](https://github.com/elastic/package-storage/blob/production/packages/aws/1.9.0/manifest.yml)

The specific steps and documentation for the creation of the package, tagging and more can be found on the Detection Rules Releasing wiki in a private repository. Refer to title "Tag and Create an Integrations PR via Go" in the documentation.
