### ISSUE TITLE
[Bug] Adjust "changelog.yml" Entries from "integrations-pr" Command

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#2351]
**Related Issues**
* https://github.com/elastic/integrations/pull/4231

**Describe the bug**
This issue is less of a bug and more of an implementation adjustment. At this time, TRADE uses the `integrations-pr` CLI command from `devtools.py` to create a integrations PR during release for rule updates.

Starting at L506, the process begins to make changes to the `changelog.yml` file and add additional entries based on the package version release. The order of keys and values in this YAML file, as implemented right now, is incorrect.

Current entries:
```
- changes:
    - description: Release security rules update
      link: https://github.com/elastic/integrations/pull/4063
      type: enhancement
  version: 8.3.1
```

Expected entries:
```
- version: 8.3.1
  changes:
    - description: Release security rules update
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4063
```

As a result, we must adjust some of the code starting at [L509](https://github.com/elastic/detection-rules/blob/9861958833f90243309ea3189432b26452e27e27/detection_rules/devtools.py#L509) so changes to the `changelog.yml` file are accurate.
