### ISSUE TITLE
[FR] Align "Data Source" tags with MITRE

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/detection-rules#3290]
**Is your feature request related to a problem? Please describe.**
I feel like aligning the `Data Source` tags with the [MITRE Data Sources](https://attack.mitre.org/datasources/) suppliments
the existing MITRE ATT&CK mappings. Further building on an existing framework.

**Describe the solution you'd like**
Allow the `Data Source` tags to have the name of the sources mentioned in [MITRE](https://attack.mitre.org/datasources/).
E.g:
```
tags = ["Data Source: Container"]
```

**Describe alternatives you've considered**
Manually updating the definition file in our repository.

**Additional context**
I don't believe it should be 100% mapped. As in only those values should be allowed. But I do think the rules where possible
should have them tagged and custom rules should have the option.

**Comment by SHolzhauer** [comment]
Thinking on how this can be done in the TOML definition

There already is something done with MITRE ATT&CK, e.g:
```toml
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1078"
reference = "https://attack.mitre.org/techniques/T1078/"
name = "Valid Accounts"
    [[rule.threat.technique.subtechnique]]
    id = "T1078.001"
    reference = "https://attack.mitre.org/techniques/T1078/001/"
    name = "Default Accounts"

[rule.threat.tactic]
id = "TA0004"
reference = "https://attack.mitre.org/tactics/TA0004/"
name = "Privilege Escalation"
```

Following the site layout what if the datasource portion is added to this:

```toml
[rule.threat.datasource]
id = "DS0015"
name = "Application Log"
reference = "https://attack.mitre.org/datasources/DS0015"
```
Which in the `tags = []` would become
```toml
tags = ["Data Source: Application Log"]
```

_some thought dumping_
I am also thinking on how this could/should/might be used in the **MITRE ATT&CK® coverage** dashboard. For example
if you have enabled rules which cover the tactic/technique but none of the data sources it could light it up red to warn for missing data. Taking that even one step further, fleet integrations could map their inputs to data sources 🤔 

What I am trying to think of is how to close the loop/create a feedback loop between detections and the datastreams coming in. Especially in situations where they are not managed by the same party/team/
