### ISSUE TITLE
[Rule Tuning] Attempts to Brute Force a Microsoft 365 User Account

### ISSUE THREAD

**Issue by ZsomborBenedek** [elastic/detection-rules#3838]
## Link to rule
https://github.com/elastic/detection-rules/blob/259efaf7165be7105a2fb990e3b7146ad6997f8f/rules/integrations/o365/credential_access_microsoft_365_brute_force_user_account_attempt.toml

## Description
The aggregation should be based on the `o365.audit.UserKey` field as it represents the unique users. Currently the user.id is used, which can be the same for multiple user, e.g. "Not Available". This transforms the results in a way which causes a lot of false positives.

Change from this:
```toml
[rule.threshold]
field = ["user.id"]
value = 10
```

To this:
```toml
[rule.threshold]
field = ["o365.audit.UserKey"]
value = 10
```

## Example Data
Screenshot (user Ids redacted for privacy):
![image](https://github.com/elastic/detection-rules/assets/44943540/0cc9ec72-8d6a-4cff-8b67-369cbbcfa424)
