### ISSUE TITLE
[FR][DAC] `kibana_export_rules` ignores path configuration in `_config.yaml`

### ISSUE THREAD

**Issue by zeuhl** [elastic/detection-rules#4696]
### Repository Feature

Detections-as-Code (DaC) - (primarily custom rule management)

## Description
The `export-rules` command does not honor the destination path configured in the `_config.yaml` file.

Currently, the mandatory `--directory` parameter must be explicitly provided and is **not automatically overridden** by the paths defined in `_config.yaml` for:

- **Standard rules**
- **Building block rules**

In contrast, for **exceptions** and **action connectors**, the tool *does* use the configuration values, as shown in `kbwrap.py`:

```python
# kbwrap.py
exceptions_directory = exceptions_directory or RULES_CONFIG.exception_dir  # line 235
action_connectors_directory = action_connectors_directory or RULES_CONFIG.action_connector_dir  # line 242
```

For rule exports, this logic is **not applied**, and the `--directory` parameter is used directly:

```python
# kbwrap.py
save_path = directory / f"{rule_name}"  # line 295
rule = TOMLRule(contents=contents, path=save_path)  # line 302
```

## Expected Behavior

- Detect if the rule is a `building_block` via the `building_block_type` flag
- Use a default export path from `_config.yaml` depending on the rule type:
  - One for **standard rules**
  - One for **building block rules**

## Current Limitation

The `_config.yaml` file defines the following structures:

```yaml
rule_dirs:
  - rules_org_A
  - rules_org_B
bbr_rules_dirs:
  - bbr_org_A
  - bbr_org_B
```

These are **lists**, which makes it ambiguous to derive a single export destination path for each rule type.

### Desired Solution

Add two new optional fields under the `directories` section of `_config.yaml` to clearly define the default export paths:

```yaml
directories:
  export_rule_folder: "rules"
  export_bbr_rule_folder: "rules_building_block"
```
